### ISSUE TITLE
Still relevant on iOS 10?

### ISSUE THREAD

**Issue by hy9be** [mbrandonw/UIResponder-KeyboardCache#3]
Hi, I am just wondering if I still need to use this code on iOS 10. I am maintaining a project initially written for iOS 6 which uses your code. I am not sure if it is safe to remove it. Thanks!

**Comment by mbrandonw** [comment]
I'm not sure actually! I haven't used this library since ios 8 and I don't think Ive noticed the keyboard delay since then!

**Comment by hy9be** [comment]
Thanks!
